AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: JSON Data API with Weekly Summary to S3

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:

  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DataItems
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST  # No capacity provisioning needed

  DataApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          DATA_TABLE_NAME: !Ref DataTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /submit
            Method: POST

  WeeklySummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: summary.lambda_handler
      Environment:
        Variables:
          DATA_TABLE_NAME: !Ref DataTable
          SUMMARY_BUCKET: !Ref SummaryBucket

  WeeklyEvent:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(7 days)
      Targets:
        - Arn: !GetAtt WeeklySummaryFunction.Arn
          Id: TargetFunctionV1
    DependsOn: WeeklySummaryFunction

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WeeklySummaryFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt WeeklyEvent.Arn

  SummaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: summary-report-bucket-1234  # Change this if necessary

